image: temporalio/gitpod-edu:1.2
additionalRepositories:
  - url: https://github.com/temporalio/reference-app-orders-go
  - url: https://github.com/temporalio/reference-app-orders-web
workspaceLocation: oms-gitpod/.main-code-workspace
tasks:
    # task links a bash configuration file to a location that is not
    # specific to this course (/etc/bash.bashrc sources it from there)
  - name: Shell configuration
    init: |
      ln /workspace/oms-gitpod/.bash.cfg /workspace/.bash.cfg
      exit;
  - name: Install pnpm
    init: |
      sudo npm install -g pnpm
      gp sync-done pnpm-install
      #exit;
  - name: install staticcheck
    init: |
      go install honnef.co/go/tools/cmd/staticcheck@latest
      exit;
    # task retrieves the project dependencies
  - name: Go Get Fetcher 
    init: |
      go get -v -t -d ./...
      exit;
    # task starts the Temporal Service via the CLI
  - name: Temporal Local Development Server
    command: |
      export TEMPORAL_NOTIFY_ON_NEW_VERSION=false
      export TEMPORAL_CORS_ORIGINS=http://localhost:3000
      temporal server start-dev \
        --ui-port 8080 \
        --db-filename /workspace/.cluster-persistence.db
    openMode: tab-after
  - name: OMS Worker 1
    command: |
      source /workspace/oms-gitpod/.bash.cfg
      clear
      echo "Starting OMS Worker #1"
      cd /workspace/reference-app-orders-go
      go run ./cmd/oms worker
    openMode: tab-after
  - name: OMS Worker 2
    command: |
      source /workspace/oms-gitpod/.bash.cfg
      clear
      echo "Starting OMS Worker #2"
      cd /workspace/reference-app-orders-go
      go run ./cmd/oms worker
    openMode: tab-after
  - name: API Server
    command: |
      source /workspace/oms-gitpod/.bash.cfg
      clear
      echo "Starting OMS API Server"
      cd /workspace/reference-app-orders-go
      go run ./cmd/oms api
    openMode: tab-after
  - name: Web Application
    command: |
      # Wait for TypeScript stuff to finish downloading
      gp sync-await pnpm-install
      # Wait for API servers to accept connections
      gp ports await 8081 && gp ports await 8082 && gp ports await 8083 && gp ports await 8084
      source /workspace/oms-gitpod/.bash.cfg
      clear
      echo "Starting OMS Web Application"
      cd /workspace/reference-app-orders-web
      pnpm i && pnpm dev
    openMode: tab-after
  - name: Display Web UI
    command: |
      echo "Waiting for server...."
      gp ports await 5173 && gp preview $(gp url 5173)
      exit;
  - name: Display README
    command: |
      gp open /workspace/reference-app-orders-go/README.md
      exit;
    openMode: split-right
  - name: Worker
    command: |
      source /workspace/oms-gitpod/.bash.cfg
      cd /workspace/reference-app-orders-go
      clear
      echo "Use this terminal to run commands.."
  - name: Terminal
    command: |
      source /workspace/oms-gitpod/.bash.cfg
      cd /workspace/reference-app-orders-go/
      clear
      echo "This is an additional terminal to run commands.."
    openMode: split-right

ports:
  - name: Temporal Server Frontend
    port: 7233
    onOpen: ignore
  - name: Temporal Web UI
    port: 8080 # custom port, as per --ui-port option above
    description: Temporal Web UI
    onOpen: ignore
    visibility: private
  - name: OMS Web Application
    description: Web application used to interact with the OMS
    port: 5173
    onOpen: ignore
    visibility: private
  # The next several have no UI and are only listed here 
  # to prevent GitPod from prompting about them
  - name: OMS Billing API Server
    port: 8081
    onOpen: ignore
  - name: OMS Order API Server
    port: 8082
    onOpen: ignore
  - name: OMS Shipment API Server
    port: 8083
    onOpen: ignore
  - name: OMS Fraud API Server
    port: 8084
    onOpen: ignore

vscode:
  extensions:
    - golang.Go
    - ms-python.python
    - ms-python.debugpy
    - redhat.java
    - vscjava.vscode-java-test
    - vscjava.vscode-java-debug
    - wingrunr21.vscode-ruby
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
